
local icons = {

  SOLID_LEFT_ARROW = utf8.char(0xe0ba),
  SOLID_LEFT_MOST = utf8.char(0x2588),
  SOLID_RIGHT_ARROW = utf8.char(0xe0bc),

  ADMIN_ICON = utf8.char(0xf49c),

  CMD_ICON = utf8.char(0xe62a),
  NU_ICON = utf8.char(0xe7a8),
  PS_ICON = utf8.char(0xe70f),
  ELV_ICON = utf8.char(0xfc6f),
  WSL_ICON = utf8.char(0xf83c),
  YORI_ICON = utf8.char(0xf1d4),
  NYA_ICON = utf8.char(0xf61a),

  VIM_ICON = utf8.char(0xe62b),
  PAGER_ICON = utf8.char(0xf718),
  FUZZY_ICON = utf8.char(0xf0b0),
  HOURGLASS_ICON = utf8.char(0xf252),
  SUNGLASS_ICON = utf8.char(0xf9df),

  PYTHON_ICON = utf8.char(0xf820),
  NODE_ICON = utf8.char(0xe74e),
  DENO_ICON = utf8.char(0xe628),
  LAMBDA_ICON = utf8.char(0xfb26),

  ZSH_ICON = '',
  VAGRANTFILE = '',
  CONF ='',
  OBJECT  = "󰅩",
  GHOST = "󰊠",
  UNIX = "", -- ebc6
  VIM = "",
  -- NVIM = "𝓝",
["sansN"] = "𝖭",
	-- NVIM = "𝗡",
	NVIM = "𝙉",

}

return icons

-- let g:startify_custom_header=[' _ _ _ ',
--
-- \'   ▕   ',
--
-- \' ▕ ███ ▕│█ ___ ___   ',
--
-- \' ▕││███ ▕│███▕│     █ ██ ',
--
-- \' ▕││ ███ ▕│███▕│▕│ ▁ ▕│   ▕│██    ',
--
-- \' ▕││ ▕│███ ▕│███▕│▕│  ▕│   ▕│██  ◢ ◣ ◢ ',
--
-- \' ▕││ ▕│ ███│███▕│  ▁▁  ▁  ██ ▜█ ██ ',
--
-- \'  ▕│ ████ ‾‾ ‾    ',
--
-- \' ▕│     ',
--
-- \' ‾ ‾ ']

 -- let s:file_node_extensions = {
 --        \ 'styl'     : '',
 --        \ 'sass'     : '',
 --        \ 'scss'     : '',
 --        \ 'htm'      : '',
 --        \ 'html'     : '',
 --        \ 'slim'     : '',
 --        \ 'haml'     : '',
 --        \ 'ejs'      : '',
 --        \ 'css'      : '',
 --        \ 'less'     : '',
 --        \ 'md'       : '',
 --        \ 'mdx'      : '',
 --        \ 'markdown' : '',
 --        \ 'rmd'      : '',
 --        \ 'json'     : '',
 --        \ 'webmanifest' : '',
 --        \ 'js'       : '',
 --        \ 'mjs'      : '',
 --        \ 'jsx'      : '',
 --        \ 'rb'       : '',
 --        \ 'gemspec'  : '',
 --        \ 'rake'     : '',
 --        \ 'php'      : '',
 --        \ 'py'       : '',
 --        \ 'pyc'      : '',
 --        \ 'pyo'      : '',
 --        \ 'pyd'      : '',
 --        \ 'coffee'   : '',
 --        \ 'mustache' : '',
 --        \ 'hbs'      : '',
 --        \ 'conf'     : '',
 --        \ 'ini'      : '',
 --        \ 'yml'      : '',
 --        \ 'yaml'     : '',
 --        \ 'toml'     : '',
 --        \ 'bat'      : '',
 --        \ 'mk'       : '',
 --        \ 'jpg'      : '',
 --        \ 'jpeg'     : '',
 --        \ 'bmp'      : '',
 --        \ 'png'      : '',
 --        \ 'webp'     : '',
 --        \ 'gif'      : '',
 --        \ 'ico'      : '',
 --        \ 'twig'     : '',
 --        \ 'cpp'      : '',
 --        \ 'c++'      : '',
 --        \ 'cxx'      : '',
 --        \ 'cc'       : '',
 --        \ 'cp'       : '',
 --        \ 'c'        : '',
 --        \ 'cs'       : '',
 --        \ 'h'        : '',
 --        \ 'hh'       : '',
 --        \ 'hpp'      : '',
 --        \ 'hxx'      : '',
 --        \ 'hs'       : '',
 --        \ 'lhs'      : '',
 --        \ 'nix'      : '',
 --        \ 'lua'      : '',
 --        \ 'java'     : '',
 --        \ 'sh'       : '',
 --        \ 'fish'     : '',
 --        \ 'bash'     : '',
 --        \ 'zsh'      : '',
 --        \ 'ksh'      : '',
 --        \ 'csh'      : '',
 --        \ 'awk'      : '',
 --        \ 'ps1'      : '',
 --        \ 'ml'       : 'λ',
 --        \ 'mli'      : 'λ',
 --        \ 'diff'     : '',
 --        \ 'db'       : '',
 --        \ 'sql'      : '',
 --        \ 'dump'     : '',
 --        \ 'clj'      : '',
 --        \ 'cljc'     : '',
 --        \ 'cljs'     : '',
 --        \ 'edn'      : '',
 --        \ 'scala'    : '',
 --        \ 'go'       : '',
 --        \ 'dart'     : '',
 --        \ 'xul'      : '',
 --        \ 'sln'      : '',
 --        \ 'suo'      : '',
 --        \ 'pl'       : '',
 --        \ 'pm'       : '',
 --        \ 't'        : '',
 --        \ 'rss'      : '',
 --        \ 'f#'       : '',
 --        \ 'fsscript' : '',
 --        \ 'fsx'      : '',
 --        \ 'fs'       : '',
 --        \ 'fsi'      : '',
 --        \ 'rs'       : '',
 --        \ 'rlib'     : '',
 --        \ 'd'        : '',
 --        \ 'erl'      : '',
 --        \ 'hrl'      : '',
 --        \ 'ex'       : '',
 --        \ 'exs'      : '',
 --        \ 'eex'      : '',
 --        \ 'leex'     : '',
 --        \ 'heex'     : '',
 --        \ 'vim'      : '',
 --        \ 'ai'       : '',
 --        \ 'psd'      : '',
 --        \ 'psb'      : '',
 --        \ 'ts'       : '',
 --        \ 'tsx'      : '',
 --        \ 'jl'       : '',
 --        \ 'pp'       : '',
 --        \ 'vue'      : '﵂',
 --        \ 'elm'      : '',
 --        \ 'swift'    : '',
 --        \ 'xcplayground' : '',
 --        \ 'tex'      : 'ﭨ',
 --        \ 'r'        : 'ﳒ',
 --        \ 'rproj'    : '鉶',
 --        \ 'sol'      : 'ﲹ',
 --        \ 'pem'      : ''
 --        \}
 --
 --  let s:file_node_exact_matches = {
 --        \ 'exact-match-case-sensitive-1.txt' : '1',
 --        \ 'exact-match-case-sensitive-2'     : '2',
 --        \ 'gruntfile.coffee'                 : '',
 --        \ 'gruntfile.js'                     : '',
 --        \ 'gruntfile.ls'                     : '',
 --        \ 'gulpfile.coffee'                  : '',
 --        \ 'gulpfile.js'                      : '',
 --        \ 'gulpfile.ls'                      : '',
 --        \ 'mix.lock'                         : '',
 --        \ 'dropbox'                          : '',
 --        \ '.ds_store'                        : '',
 --        \ '.gitconfig'                       : '',
 --        \ '.gitignore'                       : '',
 --        \ '.gitattributes'                   : '',
 --        \ '.gitlab-ci.yml'                   : '',
 --        \ '.bashrc'                          : '',
 --        \ '.zshrc'                           : '',
 --        \ '.zshenv'                          : '',
 --        \ '.zprofile'                        : '',
 --        \ '.vimrc'                           : '',
 --        \ '.gvimrc'                          : '',
 --        \ '_vimrc'                           : '',
 --        \ '_gvimrc'                          : '',
 --        \ '.bashprofile'                     : '',
 --        \ 'favicon.ico'                      : '',
 --        \ 'license'                          : '',
 --        \ 'node_modules'                     : '',
 --        \ 'react.jsx'                        : '',
 --        \ 'procfile'                         : '',
 --        \ 'dockerfile'                       : '',
 --        \ 'docker-compose.yml'               : '',
 --        \ 'rakefile'                         : '',
 --        \ 'config.ru'                        : '',
 --        \ 'gemfile'                          : '',
 --        \ 'makefile'                         : '',
 --        \ 'cmakelists.txt'                   : '',
 --        \ 'robots.txt'                       : 'ﮧ'
 --        \}
 --
 --  let s:file_node_pattern_matches = {
 --        \ '.*jquery.*\.js$'       : '',
 --        \ '.*angular.*\.js$'      : '',
 --        \ '.*backbone.*\.js$'     : '',
 --        \ '.*require.*\.js$'      : '',
 --        \ '.*materialize.*\.js$'  : '',
 --        \ '.*materialize.*\.css$' : '',
 --        \ '.*mootools.*\.js$'     : '',
 --        \ '.*vimrc.*'             : '',
 --        \ 'Vagrantfile$'          : ''
 --        \}
